version: '3'

services:

  gateway-service:
    build: ../gateway
    container_name: gateway-service
    ports:
      - '${GATE_WAY_PORT}:${GATE_WAY_PORT}'
    expose:
      - '${GATE_WAY_PORT}'

  front-end:
    build: ../frontend
    container_name: frontend
    ports:
      - '${FRONT_END_PORT}:80'
    expose:
      - '${FRONT_END_PORT}'


  budgetInstitut-service-db:
    image: ${BUDGETINSTITUT_SERVICE_DB_IMAGE_NAME}
    container_name: ${BUDGETINSTITUT_SERVICE_DB_CONTAINER_NAME}
    volumes:
      - app-data:/var/lib/mysql
    ports:
      - "${BUDGETINSTITUT_SERVICE_DB_PORT}:${BUDGETINSTITUT_SERVICE_DB_PORT}"
    environment:
      - MYSQL_DATABASE=${BUDGETINSTITUT_SERVICE_DB_NAME}
      - MYSQL_USER=${BUDGETINSTITUT_SERVICE_DB_USER}
      - MYSQL_PASSWORD=${BUDGETINSTITUT_SERVICE_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${BUDGETINSTITUT_SERVICE_DB_PASSWORD_ROOT}

  budgetInstitut-service-back:
    build: ${BUDGETINSTITUT_SERVICE_PROJECT_PATH}
    container_name: ${BUDGETINSTITUT_SERVICE_CONTAINER_NAME}
    image: ${BUDGETINSTITUT_SERVICE_IMAGE_NAME}
    ports:
      - "${BUDGETINSTITUT_SERVICE_BACK_PORT}:${BUDGETINSTITUT_SERVICE_BACK_PORT}"
    environment:
      - BUDGETINSTITUT_SERVICE_DB_URL=jdbc:mysql://budgetInstitut-service-db:3306/${BUDGETINSTITUT_SERVICE_DB_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - BUDGETINSTITUT_SERVICE_DB_USER=${BUDGETINSTITUT_SERVICE_DB_USER}
      - BUDGETINSTITUT_SERVICE_DB_PASSWORD=${BUDGETINSTITUT_SERVICE_DB_PASSWORD}
    depends_on:
      - budgetInstitut-service-db



volumes:
  app-data:

